# Generated by Django 5.1.3 on 2024-11-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
